version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.4.7
    container_name: db
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd!
      - MYSQL_PASSWORD=P@ssw0rd!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud:16.0.4-apache
    container_name: nextcloud
    ports:
      - 8080:8080
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./Apache-conf/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./Apache-conf/ports.conf:/etc/apache2/ports.conf
      - ./Apache-conf/apache2.conf:/etc/apache2/apache2.conf  
    environment:
      - MYSQL_PASSWORD=P@ssw0rd!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  nginx:
    image: nginx:1.17.9
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextcloud